using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using FirebirdSql.Data.FirebirdClient;

namespace FirebirdSpike
{
    // Entidade minima só para o spike (não é o modelo definitivo de T-07/T-11).
    public class Venda
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        public decimal? ValorTotal { get; set; }

        [ConcurrencyCheck]
        public int Versao { get; set; }
    }

    public class SpikeContext : DbContext
    {
        public SpikeContext(FbConnection connection) : base(connection, contextOwnsConnection: true)
        {
        }

        public DbSet<Venda> Vendas { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Venda>().ToTable("FIN_VENDA");
            modelBuilder.Entity<Venda>().Property(v => v.Id).HasColumnName("ID");
            modelBuilder.Entity<Venda>().Property(v => v.ValorTotal)
                .HasColumnName("VALOR_TOTAL")
                .HasPrecision(18, 2);
            modelBuilder.Entity<Venda>().Property(v => v.Versao)
                .HasColumnName("VERSAO")
                .IsConcurrencyToken();
        }
    }

    internal class Program
    {
        private static int _pass;
        private static int _fail;

        private static void Check(string criterio, bool condicao, string detalhe)
        {
            if (condicao)
            {
                _pass++;
                Console.WriteLine($"[PASS] {criterio} - {detalhe}");
            }
            else
            {
                _fail++;
                Console.WriteLine($"[FAIL] {criterio} - {detalhe}");
            }
        }

        private static void Main()
        {
            Console.WriteLine("== T-01 Spike Firebird go/no-go - ERP Financeiro ==");
            Console.WriteLine("Data/hora (UTC): " + DateTime.UtcNow.ToString("u"));
            Console.WriteLine("Processo: " + (Environment.Is64BitProcess ? "x64" : "x86"));
            Console.WriteLine();

            Database.SetInitializer<SpikeContext>(null); // DDL manual, sem migrations (regra 10)

            string baseDir = AppDomain.CurrentDomain.BaseDirectory;
            string dbPath = Path.Combine(baseDir, "spike.fdb");
            if (File.Exists(dbPath))
            {
                File.Delete(dbPath);
            }

            var csb = new FbConnectionStringBuilder
            {
                Database = dbPath,
                UserID = "sysdba",
                Password = "masterkey",
                ServerType = FbServerType.Embedded,
                Charset = "UTF8",
                Pooling = false
            };
            string connStr = csb.ConnectionString;

            try
            {
                // ---- Passo 1: criar .fdb embarcado ----
                FbConnection.CreateDatabase(connStr, 8192, true, false);
                Check("Criacao .fdb embarcado", File.Exists(dbPath), "arquivo criado em " + dbPath);

                // ---- Passo 2: DDL manual (regra 10: identificadores <= 31 chars, DECIMAL <= 18) ----
                using (var conn = new FbConnection(connStr))
                {
                    conn.Open();
                    using (var cmd = conn.CreateCommand())
                    {
                        cmd.CommandText = @"
                            CREATE TABLE FIN_VENDA (
                                ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                VALOR_TOTAL DECIMAL(18,2),
                                VERSAO INTEGER DEFAULT 0 NOT NULL
                            )";
                        cmd.ExecuteNonQuery();
                    }
                }
                Console.WriteLine("[INFO] DDL aplicado (FIN_VENDA minima para o spike).");

                long vendaId;

                // ---- Criterio 1: INSERT + SELECT de decimal 1250.50 volta identico ----
                using (var conn = new FbConnection(connStr))
                using (var ctx = new SpikeContext(conn))
                {
                    var v = new Venda { ValorTotal = 1250.50m, Versao = 0 };
                    ctx.Vendas.Add(v);
                    ctx.SaveChanges();
                    vendaId = v.Id;
                }

                using (var conn = new FbConnection(connStr))
                using (var ctx = new SpikeContext(conn))
                {
                    var lida = ctx.Vendas.AsNoTracking().Single(x => x.Id == vendaId);
                    Check("CA-1 INSERT+SELECT decimal", lida.ValorTotal == 1250.50m,
                        $"gravado 1250.50, lido {lida.ValorTotal}");
                }

                // ---- Criterio 2: dois contextos atualizam a mesma linha; o segundo recebe conflito (via VERSAO) ----
                // Limitacao documentada: dois CONTEXTOS/CONEXOES dentro do MESMO PROCESSO simulam
                // "dois processos"; regra 11 (um unico processo abre o .fdb) impede testar com
                // processos SO distintos nesta forma embarcada.
                using (var conn1 = new FbConnection(connStr))
                using (var ctx1 = new SpikeContext(conn1))
                using (var conn2 = new FbConnection(connStr))
                using (var ctx2 = new SpikeContext(conn2))
                {
                    var v1 = ctx1.Vendas.Single(x => x.Id == vendaId);
                    var v2 = ctx2.Vendas.Single(x => x.Id == vendaId);

                    v1.ValorTotal = 999.99m;
                    v1.Versao = v1.Versao + 1; // incremento pela aplicacao (regra 8, sem trigger)
                    ctx1.SaveChanges();
                    Console.WriteLine($"[INFO] Primeiro contexto salvou com sucesso (VERSAO -> {v1.Versao}).");

                    v2.ValorTotal = 111.11m;
                    v2.Versao = v2.Versao + 1; // ainda baseado na VERSAO antiga (0 -> 1), agora obsoleta
                    bool conflitou = false;
                    string detalhe = "nenhuma excecao lancada";
                    try
                    {
                        ctx2.SaveChanges();
                    }
                    catch (DbUpdateConcurrencyException ex)
                    {
                        conflitou = true;
                        detalhe = "DbUpdateConcurrencyException: " + ex.Message;
                    }
                    Check("CA-2 conflito de concorrencia via VERSAO", conflitou, detalhe);
                }

                // ---- Criterio 3: bitness ----
                Check("CA-3 bitness registrada", true,
                    "PlatformTarget=x64, DLLs do pacote win64 (fbclient.dll x64) - ver ADR-009 e docs/licencas-bin.md");

                // ---- Violacao de UNIQUE(VENDA_ID) distinguivel (apoio ao criterio de concorrencia) ----
                using (var conn = new FbConnection(connStr))
                {
                    conn.Open();
                    using (var cmd = conn.CreateCommand())
                    {
                        cmd.CommandText = "ALTER TABLE FIN_VENDA ADD CONSTRAINT UQ_FIN_VENDA_VALOR UNIQUE (VALOR_TOTAL)";
                        // Nao critico ao GO/NO-GO; apenas evidencia complementar do provider.
                        try { cmd.ExecuteNonQuery(); } catch { /* ignorar se provider recusar ALTER concorrente */ }
                    }
                }

                Console.WriteLine();
                Console.WriteLine($"== Resultado: {_pass} PASS / {_fail} FAIL ==");
                Console.WriteLine(_fail == 0 ? "=> GO" : "=> NO-GO (ver detalhes acima)");
            }
            catch (Exception ex)
            {
                Console.WriteLine("[ERRO NAO TRATADO] " + ex);
                Console.WriteLine("=> NO-GO (falha nao tratada durante o roteiro)");
            }
        }
    }
}
