-- ERP Financeiro — database/01-schema.sql
-- DDL manual (regra 10 do TASK.md, Seção 1) — sem migrations. Firebird 3.0 embarcado.
-- Modelo de dados: SDD.md Seção 5 · Concorrência: ADR-005 · Colunas anuláveis: ADR-007 (D-08)
-- Confirmação de sintaxe (identity/generator, DECIMAL(18,2)): ADR-009 (spike T-01, GO).
--
-- Convenção do script (isql): SET TERM troca o terminador de comando para ^ dentro
-- dos blocos PSQL (CREATE TRIGGER), evitando conflito com os ";" internos do corpo.
-- Aplicado por: isql -i 01-schema.sql, ou em runtime por FbScript/FbBatchExecution
-- (FirebirdSql.Data.Isql), que entendem essa mesma convenção (ver T-12 DbInitializer).
--
-- Regras de banco (TASK.md Seção 1, regra 10): identificadores <= 31 chars (constraints
-- e índices nomeados explicitamente), DECIMAL <= 18, TINYINT -> SMALLINT,
-- DATETIME2 -> TIMESTAMP (UTC). CLIENTE_ID e VALOR_TOTAL anuláveis (ADR-007/D-08).
-- VERSAO incrementada pela aplicação, sem trigger de versão (regra 8, SDD 2.5, ADR-005).

SET TERM ^ ;

-- =====================================================================
-- FIN_VENDA
-- =====================================================================
CREATE TABLE FIN_VENDA (
    ID                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    VENDA_ID               VARCHAR(50) NOT NULL,
    CLIENTE_ID             VARCHAR(50),                  -- NULL: ADR-007/D-08 (venda desconhecida cancelada)
    VALOR_TOTAL            DECIMAL(18,2),                 -- NULL: ADR-007/D-08 (idem)
    STATUS                 SMALLINT NOT NULL,             -- 0 Pendente, 1 Quitada, 2 Cancelada (SDD 5)
    DATA_RECEBIMENTO       TIMESTAMP NOT NULL,             -- UTC
    DATA_QUITACAO          TIMESTAMP,                      -- UTC, NULL até quitar
    DATA_CANCELAMENTO      TIMESTAMP,                      -- UTC, NULL até cancelar
    MOTIVO_CANCELAMENTO    VARCHAR(500),
    VERSAO                 INTEGER DEFAULT 0 NOT NULL,     -- concorrência otimista; app incrementa (sem trigger)
    CONSTRAINT PK_FIN_VENDA PRIMARY KEY (ID),
    CONSTRAINT UQ_FIN_VENDA_VENDA_ID UNIQUE (VENDA_ID),
    CONSTRAINT CK_FIN_VENDA_STATUS CHECK (STATUS IN (0, 1, 2))
)^

-- =====================================================================
-- FIN_VENDA_ITEM
-- =====================================================================
CREATE TABLE FIN_VENDA_ITEM (
    ID                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    VENDA_REF              BIGINT NOT NULL,
    PRODUTO_ID              VARCHAR(50) NOT NULL,
    QUANTIDADE             INTEGER NOT NULL,
    PRECO_UNITARIO         DECIMAL(18,4) NOT NULL,
    CONSTRAINT PK_FIN_VENDA_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_FIN_VENDA_ITEM_VENDA FOREIGN KEY (VENDA_REF)
        REFERENCES FIN_VENDA (ID) ON DELETE CASCADE,
    CONSTRAINT CK_FIN_VENDA_ITEM_QTD CHECK (QUANTIDADE > 0),
    CONSTRAINT CK_FIN_VENDA_ITEM_PRECO CHECK (PRECO_UNITARIO >= 0)
)^

-- =====================================================================
-- FIN_VENDA_HISTORICO (append-only: repositório expõe só Adicionar — regra 8)
-- =====================================================================
CREATE TABLE FIN_VENDA_HISTORICO (
    ID                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    VENDA_REF              BIGINT NOT NULL,
    OPERACAO               SMALLINT NOT NULL,              -- 0 Recebida, 1 Quitação, 2 Cancelamento (SDD 5)
    STATUS_ANTERIOR        SMALLINT,                        -- NULL na criação
    STATUS_NOVO            SMALLINT NOT NULL,
    DATA_HORA              TIMESTAMP NOT NULL,              -- UTC
    MOTIVO                 VARCHAR(500),
    CORRELATION_ID         VARCHAR(50),
    CONSTRAINT PK_FIN_VENDA_HISTORICO PRIMARY KEY (ID),
    CONSTRAINT FK_FIN_VENDA_HIST_VENDA FOREIGN KEY (VENDA_REF)
        REFERENCES FIN_VENDA (ID) ON DELETE CASCADE,
    CONSTRAINT CK_FIN_VENDA_HIST_OPER CHECK (OPERACAO IN (0, 1, 2))
)^

SET TERM ; ^

-- =====================================================================
-- Índices nomeados (regra 10; consultas por cliente/status/período — SDD 5, CA-07.x, T-23/T-57)
-- =====================================================================
CREATE INDEX IDX_FIN_VENDA_CLIENTE ON FIN_VENDA (CLIENTE_ID);
CREATE INDEX IDX_FIN_VENDA_STATUS ON FIN_VENDA (STATUS);
CREATE INDEX IDX_FIN_VENDA_DATA_REC ON FIN_VENDA (DATA_RECEBIMENTO);

-- Índices de apoio às FKs (join item/histórico -> venda); não exigidos pelo critério de
-- aceite de T-05, mas nomeados explicitamente (regra 10) para evitar full scan em T-14/T-23/T-24.
CREATE INDEX IDX_FIN_VENDA_ITEM_VENDA ON FIN_VENDA_ITEM (VENDA_REF);
CREATE INDEX IDX_FIN_VENDA_HIST_VENDA ON FIN_VENDA_HISTORICO (VENDA_REF);

-- =====================================================================
-- Defesa em profundidade: histórico append-only (SDD 5, "opcionalmente triggers
-- BEFORE UPDATE/DELETE que lançam exceção"). O repositório (T-14/Application) já
-- expõe só Adicionar; os triggers reforçam a regra mesmo contra acesso direto ao banco.
-- =====================================================================
SET TERM ^ ;

CREATE EXCEPTION EX_HIST_APPEND_ONLY 'FIN_VENDA_HISTORICO e append-only: UPDATE/DELETE nao permitido.'^

CREATE TRIGGER TRG_FIN_VENDA_HIST_NO_UPD FOR FIN_VENDA_HISTORICO
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    EXCEPTION EX_HIST_APPEND_ONLY;
END^

CREATE TRIGGER TRG_FIN_VENDA_HIST_NO_DEL FOR FIN_VENDA_HISTORICO
ACTIVE BEFORE DELETE POSITION 0
AS
BEGIN
    EXCEPTION EX_HIST_APPEND_ONLY;
END^

SET TERM ; ^
